# Generated by Django 4.0.3 on 2022-03-14 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hotelname', models.CharField(max_length=100)),
                ('checkin_date', models.CharField(max_length=20)),
                ('checkout_date', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guest_name', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('Reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_list', to='hotelapp.reservation')),
            ],
        ),
    ]
